# Generated by Django 3.2 on 2021-06-30 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('display_name', models.CharField(max_length=10, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('department', models.CharField(choices=[('general', 'General'), ('science', 'Science'), ('business', 'Business'), ('humanities', 'Humanities')], max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.classinfo')),
            ],
            options={
                'unique_together': {('class_name',)},
            },
        ),
    ]
