# Generated by Django 3.2 on 2021-06-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='uczen',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='typ_nieobecnosci',
            field=models.CharField(choices=[('śpóźnienie', 'Śpóźnienie'), ('nieobecność', 'Nieobecność'), ('nieobecność usprawiedliwiona', 'Nieobecność usprawiedliwiona')], default='spóźnienie', max_length=30),
        ),
    ]
